apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring 
  namespace: kube-system
spec:
  jobImage: %%REGISTRY%%/%%STAGE%%/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://%%CLUSTER%%.%%DOMAIN%%:9345/static/charts/rancher-monitoring-v9.4.203.tgz
  targetNamespace: cattle-monitoring-system
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
        clusterName: %%CLUSTER%%
      rbac:
        ## Create RBAC resources for ServiceAccounts and users 
        ##
        create: true
    
        userRoles:
          ## Create default user ClusterRoles to allow users to interact with Prometheus CRs, ConfigMaps, and Secrets
          create: true
          ## Aggregate default user ClusterRoles into default k8s ClusterRoles
          aggregateToDefaultRoles: true
    
        pspEnabled: true
    grafana:
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        size: 1G
        storageClassName: vsphere
        subPath: null
        type: statefulset
    prometheus:
      prometheusSpec:
        retentionSize: 1GiB
        storageSpec:
         volumeClaimTemplate:
           spec:
             storageClassName: vsphere
             accessModes: ["ReadWriteOnce"]
             resources:
               requests:
                 storage: 10Gi
    rke2ControllerManager:
      enabled: true
    rke2Etcd:
      enabled: true
    rke2Proxy:
      enabled: true
    rke2Scheduler:
      enabled: true
