apiVersion: v1
kind: Namespace
metadata:
  name: cattle-resources-system
---
apiVersion: v1
kind: Secret
metadata:
  name: rancher-backup-minio-secret
  namespace: cattle-resources-system
type: Opaque
data:
  accessKey: cmFuY2hlcg==
  secretKey: cmFuY2hlcjEyMzQ=

