apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
  metadata:
    name: syslog01.suse
    namespace: cattle-logging-system
  spec:
    syslog:
      buffer:
        total_limit_size: 2GB
        flush_thread_count: 8
        timekey: 10m
        timekey_use_utc: true
        timekey_wait: 1m
      format:
        app_name_field: kubernetes.pod_name
        hostname_field: custom-cluster-name
        log_field: message
        rfc6587_message_size: false
      host: syslog01.suse
      insecure: true
      port: 514
      transport: udp
kind: List
---
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterFlow
  metadata:
    name: syslog01.suse
    namespace: cattle-logging-system
  spec:
    filters:
    - record_transformer:
        records:
        - custom-cluster-name: %%CLUSTER%%
    globalOutputRefs:
    - syslog01.suse
kind: List
