apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rancher-logging-fluent-psp-role
  namespace: cattle-logging-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - system-unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-logging-fluent-psp-binding
  namespace: cattle-logging-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rancher-logging-fluent-psp-role
subjects:
- kind: ServiceAccount
  name: rancher-logging-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-root-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-fluentbit
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-rke2-containers-fluentd
  namespace: cattle-logging-system
- kind: ServiceAccount
  name: rancher-logging-rke2-journald-fluentd
  namespace: cattle-logging-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-logging
  namespace: kube-system
spec:
  jobImage: %%REGISTRY%%/%%STAGE%%/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://%%CLUSTER%%.%%DOMAIN%%:9345/static/charts/rancher-logging-100.1.3+up3.17.7.tgz
  targetNamespace: cattle-logging-system
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
    additionalLoggingSources:
      rke2:
        enabled: true
    rbac:
      psp:
        enabled: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    tolerations:
      - key: cattle.io/os
        operator: "Equal"
        value: "linux"
        effect: NoSchedule
      - effect: NoExecute
        key: CriticalAddonsOnly
        value: "true"
    fluentd:
      resources:
        limits:
          cpu: 1000m
          memory: 800M
        requests:
          cpu: 500m
          memory: 400M
    fluentbit:
      resources:
        limits:
          cpu: 200m
          memory: 200M
        requests:
          cpu: 100m
          memory: 100M
      tolerations:
        - effect: NoExecute
          key: CriticalAddonsOnly
          value: "true"
    fluentbit_tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
