apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring-crd
  namespace: kube-system
spec:
  jobImage: %%REGISTRY%%/%%STAGE%%/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://%%CLUSTER%%.%%DOMAIN%%:9345/static/charts/rancher-monitoring-crd-v100.0.0+up16.6.0.tgz
  targetNamespace: cattle-monitoring-system
  valuesContent: |-
    # Default values for rancher-monitoring-crd.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    
    global:
      cattle:
        systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
    
        #    image:
        #      repository: rancher/kubectl
        #      tag: v1.18.6
