apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-logging-crd
  namespace: kube-system
spec:
  jobImage: %%REGISTRY%%/%%STAGE%%/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://%%CLUSTER%%.%%DOMAIN%%:9345/static/charts/rancher-logging-crd-v100.0.0+up3.12.0.tgz
  targetNamespace: cattle-logging-system
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
