apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn-crd
  namespace: kube-system
spec:
  jobImage: registry01.suse:5000/rke-int/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://rke-int.suse:9345/static/charts/longhorn-crd-v1.1.001.tgz
  targetNamespace: longhorn-system
