apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring 
  namespace: kube-system
spec:
  jobImage: registry01.suse:5000/rke-int/docker.io/rancher/klipper-helm:v0.4.3
  chart: https://rke-int.suse:9345/static/charts/rancher-monitoring-v9.4.203.tgz
  targetNamespace: cattle-monitoring-system
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "registry01.suse:5000/rke-int/docker.io"
        clusterName: rke-int
      rbac:
        ## Create RBAC resources for ServiceAccounts and users 
        ##
        create: true
    
        userRoles:
          ## Create default user ClusterRoles to allow users to interact with Prometheus CRs, ConfigMaps, and Secrets
          create: true
          ## Aggregate default user ClusterRoles into default k8s ClusterRoles
          aggregateToDefaultRoles: true
    
        pspEnabled: true
    grafana:
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        size: 1G
        storageClassName: longhorn
        subPath: null
        type: statefulset
    prometheus:
      prometheusSpec:
        retentionSize: 4GiB
        storageSpec:
         volumeClaimTemplate:
           spec:
             storageClassName: longhorn
             accessModes: ["ReadWriteOnce"]
             resources:
               requests:
                 storage: 5Gi
    rke2ControllerManager:
      enabled: true
    rke2Etcd:
      enabled: true
    rke2Proxy:
      enabled: true
    rke2Scheduler:
      enabled: true
