apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
        clusterName: %%CLUSTER%%
      systemDefaultRegistry: "%%REGISTRY%%/%%STAGE%%/docker.io"
    cilium:
      ipam:
        mode: "kubernetes"
