apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    clusterCIDR: %%CLUSTERCIDR%%
    ipvs:
      strictARP: true
