apiVersion: v1
kind: Namespace
metadata:
  name: cattle-resources-system
---
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup-hourly
  namespace: cattle-resources-system
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 168
  schedule: 0 * * * *
type: resources.cattle.io.backup
---
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-backup-one-time
  namespace: cattle-resources-system
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
type: resources.cattle.io.backup

