apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-logging-crd
  namespace: kube-system
spec:
  jobImage: registry01.suse:5000/rke-prod/docker.io/rancher/klipper-helm:v0.4.3-build20210225
  chart: https://rke-prod.suse:9345/static/charts/rancher-logging-crd-v3.9.000.tgz
  targetNamespace: cattle-logging-system
  valuesContent: |-
    global:
      cattle:
        systemDefaultRegistry: "registry01.suse:5000/rke-prod/docker.io"
