apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring-crd
  namespace: kube-system
spec:
  jobImage: registry01.suse:5000/rke-test/docker.io/rancher/klipper-helm:v0.4.3-build20210225
  chart: https://rke-test.suse:9345/static/charts/rancher-monitoring-crd-v9.4.203.tgz
  targetNamespace: cattle-monitoring-system
  valuesContent: |-
    # Default values for rancher-monitoring-crd.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    
    global:
      cattle:
        systemDefaultRegistry: "registry01.suse:5000/rke-test/docker.io"
    
    image:
      repository: rancher/kubectl
      tag: v1.18.6
