apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      replicaCount: 3
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
    defaultBackend:
      replicaCount: 3
